name: "Azure Machine Learning Workspace Connector"
description: "Connect to or create a Azure Machine Learning Workspace with this GitHub Action"
author: "Marvin Buss"
inputs:
  parametersFile:
    description: "JSON file including the parameters of the compute."
    required: true
    default: "compute.json"
runs:
  using: "docker"
  image: "Dockerfile"
